kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresql-data
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: postgres-secret
          image: "registry.redhat.io/rhel9/postgresql-16:9.6"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
