kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  namespace: feast
data:
  POSTGRES_DB: ZmVhc3Q=
  POSTGRES_PASSWORD: ZmVhc3Q=
  POSTGRES_USER: ZmVhc3Q=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: feast-data-stores
  namespace: feast
data:
  postgres: aG9zdDogcG9zdGdyZXMuZmVhc3Quc3ZjLmNsdXN0ZXIubG9jYWwKcG9ydDogNTQzMgpkYXRhYmFzZTogZmVhc3QKZGJfc2NoZW1hOiBwdWJsaWMKdXNlcjogZmVhc3QKcGFzc3dvcmQ6IGZlYXN0Cg==
  sql: cGF0aDogcG9zdGdyZXNxbCtwc3ljb3BnOi8vZmVhc3Q6ZmVhc3RAcG9zdGdyZXMuZmVhc3Quc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9mZWFzdApjYWNoZV90dGxfc2Vjb25kczogNjAwCnNxbGFsY2hlbXlfY29uZmlnX2t3YXJnczoKICBlY2hvOiBmYWxzZQogIHBvb2xfcHJlX3Bpbmc6IHRydWUK
type: Opaque
